## Inleiding

Exceptions zijn gebeurtenissen die we niet willen of verwachten tijdens het compileren of de uitvoering van je programma. In Java hebben we een manier om dit te kunnen verwerken `Exception handling` Exceptions kunnen we dus opvangen om deze te verwerken in het programma.

Voorbeelden van waarom er een exception kan voorkomen:

- Foutieve invoer van een gebruiker
- Verlies van netwerk verbinding
- Het openen van een onvindbare file.
- **En nog veel meer!**

Naast exceptions hebben we ook `errors`. Als het programma een error veroorzaakt dan is dit anders als een exception. Een error ligt meestal niet bij de programmeur van het programma.

Voorbeelden van een error kan zijn:

- memory leaks
- stack overflow errors
- Geen of te weinig geheugen
- Code fouten (Compile errors)

**BELANGRIJK: Als er een error voorkomt gaan we deze niet opvangen/ behandelen!**

In het kort, een error geeft een ernstig probleem aan dat een toepassing niet zou moeten proberen op te lossen. Een exception geeft voorwaarden aan die een toepassing zou kunnen opvangen.

[Link naar documentatie exceptions](https://cr.openjdk.java.net/~iris/se/15/spec/fr/java-se-15-fr-spec/api/java.base/java/lang/Exception.html)

## Soorten exceptions

Hieronder vind je de hiërarchie van exceptions and errors. Je ziet dat beide subklassen zijn van Throwable, dit is de base class. Exceptions is de klas dit we gaan behandelen of te wel **catchen**. Bij Errors is het **sterk afgeraden** om die te behandelen zoals je hieronder ook kunt zien.

![](Treeview%20exceptions.png)

Nu gaan we kijken naar de verschillende types van exceptions. Exceptions delen we op in 2 verschillende categorieën:

- built-in exceptions
- User-defined exceptions

Hieronder hebben een voorbeeld hoe dit is opgebouwd.

![](types%20of%20exceptions.png)

We gaan nu even doorlopen wat dit schema betekend. We beginnen eerst met de built-in exception. Deze worden ook weer opgesplitst in 2 categorieën checked en unchecked.
<div style='page-break-after: always;'></div>

### Checked exceptions

Deze worden ook wel compile-time exceptions genoemd omdat deze exceptions worden gecontroleerd door de compiler. Bijvoorbeeld een ClassNotFoundException.

### Unchecked exception

Deze exceptions werken juist het tegenovergestelde van de checked exceptions. De compiler gaat deze niet controleren en als we deze niet behandelen zal het programma gewoon compileren. Dit word ook wel een runtime exception genoemd. Hieronder zie je een voorbeeld van een ArithmeticException, dat een Unchecked exception is.

```java
public static void main(String[] args) {

	int num = 5;

	// It's not possible to divide by 0. This will give a ArithmeticException
	int result = num / 0;

	System.out.println(result);

}

// exception message in the command line
/*
Exception in thread "main" java.lang.ArithmeticException: / by zero
 at be.intecbrussel.MainApp.main(MainApp.java:9)
*/
```

<div style='page-break-after: always;'></div>

## Methodes om de exception informatie te printen

| Methode | Beschrijving |
|---|---|
| printStackTrace() | Dit zal de volledige informatie tonen |
| toString() | Dit print alleen de naam van de exception uit met de beschrijving ervan |
| getMessage() | Deze methode print alleen de beschrijving uit. |

Zie hieronder het voorbeeld:

```java
public static void main(String[] args) {

	try {
		int num = 5;

		int result = num / 0;

		System.out.println(result);

	} catch (ArithmeticException arithmeticException) {
		System.out.println(arithmeticException.toString());

	}

}

// Dit is wat we zien in de terminal:
// java.lang.ArithmeticException: / by zero
```

## Try-catch block

Syntax voor een try-catch block vind je hieronder.

```java
try {
    // block of code to monitor for errors
    // the code you think can raise an exception
} catch (ExceptionType1 exOb) {
    // exception handler for ExceptionType1
} catch (ExceptionType2 exOb) {
    // exception handler for ExceptionType2
}
// optional
finally {  // block of code to be executed after try block ends 
}
```

Belangrijk om te weten over een try-catch block:

- Een try block kan 0 of meerdere catch blocks bevatten.
- In een methode is het mogelijk om meerdere statements te hebben die een exception kunnen gooien. Zorg dat elke statement zoveel mogelijk hun eigen try-block krijgen.

## Finally-block

Een try-catch kan alleen maar **1** finally block hebben.

Het finally block word gebruikt om belangrijke code te laten runnen.

Belangrijk om te weten is dat een finally-block een **optioneel** deel is in een try-catch block.

Ongeacht of een exception wordt opgevangen of niet, de finally block gaat zijn code uitvoeren. Handig voor logs te verzenden of om connecties te sluiten zoals bijvoorbeeld een database.

De finally block zal niet uitvoeren als je het proces stopt voor dat de code de finally block kan bereiken, of dat je code via een fatal error stopt.

## Meerdere exceptions opvangen

Als je meerdere exceptions wil opvangen met een try block moet je goed opletten op de volgorde. De super klassen komen altijd **NA** de subklassen in een try-catch block. Als je de volgorde probeert om te draaien zal Intellij dit niet toelaten.

Probeer het maar eens met het volgende voorbeeld:

```java
// This wil work because Exception class is de super class of ArithmeticException.
    public static void main(String[] args) {

        try {
            int num = 5;

            int result = num / 0;

            System.out.println(result);

        } catch (ArithmeticException arithmeticException) {
            arithmeticException.printStackTrace();

        } catch (Exception exception) {
            exception.printStackTrace();
        }
        
    }
```

<div style='page-break-after: always;'></div>

Je kunt ook 2 exceptions in dezelfde catch plaatsen. Alleen de 1ste fout wordt opgevangen. De rest wordt genegeerd. Let op: je kunt geen exceptions combineren met een lager of hoger nivieu. Probeer eens 'NumberFormatException' hieronder te vervangen door 'Exception'. 

```java
    public static void main(String[] args) {

        try {
            int num = Integer.parseInt("6,3");

            int result = 5 / 0;

            System.out.println(result);

        } catch (ArithmeticException | NumberFormatException anException) {
            anException.printStackTrace();

        }

    }
```

## Throw en throws keywords

De `throw` keyword wordt gebruikt om uitdrukkelijk een exception te gooien. We kunnen checked of unchecked exceptions gooien maar voornamelijk word het gebruikt bij eigen gemaakte exceptions. Wanneer een exception is gegooid met keyword throw, word the executie van het programma gestopt en dit verwezen naar het dichtstbijzijnde try-catch block met overeenkomende type van exception. Als dit er niet is gaat over naar de default exception handler.

Met keyword `throws` wordt juist in de method signature duidelijk gemaakt dat er een mogelijkheid is dat deze exception gegooid kan worden. Met `throws` kunnen we ook meerdere exceptions declareren, maar met keyword `throw` niet. We kunnen maar een exception gooien. Het voordeel van dit is dat we niet overal een try-catch block hoeven te implementeren als we gebruik maken van `throw`en `throws`. Dit zorgt dan ook weer voor clean coding.

Hieronder zie je een voorbeeld van keyword `throw`:

<div style='page-break-after: always;'></div>

```java
    public static void main(String args[]) {

        check(12);

    }

    public static void check(Integer num) throws ArithmeticException{

        if(num < 18){

            // throw exception using java throw keyword
            throw new ArithmeticException("You are not allowed to vote!");
        }

        else {
            System.out.println("You can vote!!");
        }

    }

```

Hieronder zie je een voorbeeld van keyword `throws` wat bad practice is omdat we geen exception handeling doen in de main class. Dit is omdat er geen klas na de main class is die de exception kan opvangen.

```java

// 
    public static void main(String[] args) throws InterruptedException {

        Thread.sleep(100);

        System.out.println("Print successfully");
    }

```

<div style='page-break-after: always;'></div>

## Je eigen exceptions maken

Hieronder ga je 2 voorbeelden zien van een eigen ontworpen checked en unchecked exception. Je moet even goed kijken van het verschil tussen de 2 voorbeelden. Bij de unchecked exception gebruiken we RuntimeException in plaats van Exception en in de main hebben we geen try-catch block.

### Creëer een eigen ontworpen checked exception

```java
package be.intecbrussel;

// create a checked exception class
public class CustomException extends Exception{

    public CustomException(String message) {
        super(message);
    }

}
```

```java
package be.intecbrussel;

import java.util.ArrayList;
import java.util.Arrays;

public class LanguageChecker {

    ArrayList<String> languages = new ArrayList<>(Arrays.asList("Java", "Python", "JavaScript"));

    public void checkLanguage(String language) throws CustomException {

        // throw exception if language already present in ArrayList
        if (languages.contains(language)) {
            throw new CustomException(language + " already exists");
        } else {
            // insert language to ArrayList
            languages.add(language);
            System.out.println(language + " is added to the ArrayList");

        }

    }

}
```

<div style='page-break-after: always;'></div>

```java
package be.intecbrussel;


public class MainApp {

    public static void main(String[] args) {

        LanguageChecker checker = new LanguageChecker();

        try {
            checker.checkLanguage("C#");
            checker.checkLanguage("Java");
        }

        catch(CustomException customException) {
            System.out.println("[" + customException + "] Exception Occurred");

        }

    }

}
```

### Creëer een eigen ontworpen unchecked exception

```java

package be.intecbrussel.unchecked;

// create a unchecked exception class
class CustomException extends RuntimeException {

    public CustomException(String message) {

        super(message);

    }

}

```

<div style='page-break-after: always;'></div>

```java
package be.intecbrussel.unchecked;

import java.util.ArrayList;
import java.util.Arrays;

public class LanguageChecker {

    ArrayList<String> languages = new ArrayList<>(Arrays.asList("Java", "Python", "JavaScript"));

    public void checkLanguage(String language) {

        if (languages.contains(language)) {
            throw new CustomException(language + " already exists");

        } else {

            languages.add(language);
            System.out.println(language + " is added to the ArrayList");
        }

    }

}
```

```java
package be.intecbrussel.unchecked;

public class MainApp {

    public static void main(String[] args) {

        LanguageChecker checker = new LanguageChecker();

        checker.checkLanguage("C#");
        checker.checkLanguage("Java");


    }

}
```
